const swaggerAutogen = require('swagger-autogen')();
const dotenv = require('dotenv');

dotenv.config();

const doc = {
    info: {
        version: '1.0.0',
        title: ' api',
        description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.'
    },
    host: process.env.SWAGGER_URL,
    basePath: '/',
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],

    tags: [
        {
            name: 'User',
            description: 'Endpoints'
        }
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: 'apiKey',
            in: 'header', // can be "header", "query" or "cookie"
            name: 'X-API-KEY', // name of the header, query parameter or cookie
            description: 'any description...'
        }
    },
    definitions: {
        addUserController:{
           
                "first_name": "tj",
                "last_name": "name",
                "address": "indore",
                "email_id": "tj123@gmail.com",
                "status_enum_id": 1,
                "phone_number":12423435
              
        },
        updateUserController:{
            
                "first_name": "tj",
                "last_name": "name",
                "address": "indore",
                "email_id": "tj123@gmail.com",
                "status_enum_id": 1,
                "phone_number":12423435,
                "id":1
              
        }

    }
};

const outputFile = './swagger_output.json';
const endpointsFiles = [
    './src/routes/routes.ts'
];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.ts'); // Your project's root file
});
